### ISSUE TITLE
README.md refers to bin/ directory which doesnt exist

### ISSUE THREAD

**Issue by jayvdb** [mementoweb/pymemento#3]
It appears that the bin directory was never created.
Are there some useful scripts which are intended to be added?
Or should this be removed from README.md?

**Comment by shawnmjones** [comment]
Thanks for your interest in pymemento!

Yes, the bin directory never got added.  I am updating the README.md.

**Comment by shawnmjones** [comment]
At some point in the future, we will develop the content of the bin directory, but you are correct, the documentation was misleading.
